/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AASTHA
 */import java.sql.*;
import javax.swing.JOptionPane;
public class nsr extends javax.swing.JFrame {

    /**
     * Creates new form nsr
     */
    Connection con;
    public nsr() {
        initComponents();
        okb.setVisible(false);
        updateb.setVisible(false);
        updateb1.setVisible(false);
        try
        {
        Class.forName("oracle.jdbc.driver.OracleDriver");
      String url="jdbc:oracle:thin:@localhost:1521";
       con=DriverManager.getConnection(url, "system","aastha");
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sn = new javax.swing.JTextField();
        branc = new javax.swing.JComboBox<>();
        em = new javax.swing.JTextField();
        rn = new javax.swing.JTextField();
        sem = new javax.swing.JComboBox<>();
        mob = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        zip = new javax.swing.JTextField();
        submitb = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        updateb = new javax.swing.JButton();
        okb = new javax.swing.JButton();
        addrs = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mnm = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fnm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        categ = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        blg = new javax.swing.JComboBox<>();
        state = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        dobi = new javax.swing.JTextField();
        updateb1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("UserName");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Password");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel2.setText("Student Name");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel3.setText("Enrollment No.");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel4.setText("Branch");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel5.setText("Email ");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel6.setText("Semester");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel8.setText("City");

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel9.setText("Mobile No.");

        sn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N

        branc.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        branc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.E.", "C.S.E.", "E.E.E.", "I.T.", "M.E.", "E.E.", "E.T.C.", "ET.&T." }));
        branc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brancItemStateChanged(evt);
            }
        });
        branc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brancActionPerformed(evt);
            }
        });

        em.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N

        rn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N

        sem.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        mob.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N

        city.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel10.setText("State");

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel11.setText("Zip Code");

        zip.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N

        submitb.setBackground(new java.awt.Color(0, 51, 204));
        submitb.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        submitb.setText("Submit");
        submitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 204));
        jButton3.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        updateb.setBackground(new java.awt.Color(0, 51, 204));
        updateb.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        updateb.setText("Update");
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });

        okb.setBackground(new java.awt.Color(204, 204, 204));
        okb.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        okb.setForeground(new java.awt.Color(0, 0, 255));
        okb.setText("OK");
        okb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbActionPerformed(evt);
            }
        });

        addrs.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 16)); // NOI18N
        jLabel14.setText("Father's Name");

        mnm.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        mnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 16)); // NOI18N
        jLabel15.setText("Mother's Name");

        fnm.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel16.setText("Category");

        categ.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        categ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "OBC", "ST ", "SC" }));

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 16)); // NOI18N
        jLabel17.setText("Blood Group");

        blg.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        blg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        state.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N
        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andaman & Nicobar", "Andhra Pradesh", "Arunanchal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "New Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu&Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshwadeep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha ", "Puducherry", "Punjab", "Rajasthan ", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal" }));

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 16)); // NOI18N
        jLabel18.setText("Gender");

        gender.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 16)); // NOI18N
        jLabel19.setText("D.O.B(dd-mm-yyyy)");

        dobi.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N

        updateb1.setBackground(new java.awt.Color(0, 51, 204));
        updateb1.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        updateb1.setText("Delete");
        updateb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateb1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("                            Student Registration form");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateb1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(okb))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(categ, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dobi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(blg, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(74, 74, 74)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mnm, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fnm, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(branc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addrs, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(197, Short.MAX_VALUE))))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(em, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addrs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void submitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbActionPerformed
      try
      {
      long m=0;
      int flag=0;
      Statement st=con.createStatement();
      String stnm=sn.getText();
      String sfnm=fnm.getText();
      String smnm=mnm.getText();
      String blgr=(String)blg.getSelectedItem();
      String cat=(String)categ.getSelectedItem();
      String enroll=rn.getText();
      String email=em.getText();
      String mobl=mob.getText();
      int len=mobl.length();
      if(len==10)
      {
            m=Long.parseLong(mob.getText());
      }
      else 
      {
          JOptionPane.showMessageDialog(this,"Enter 10-digits mobile no. only");
          flag=1;
      }
      
      int z=Integer.parseInt(zip.getText());
      String add=addrs.getText();
      String c=city.getText();
      String s=(String)state.getSelectedItem();
      String getbranch=(String)branc.getSelectedItem();
      int getsem=Integer.parseInt((String)sem.getSelectedItem());
      String gend=(String)gender.getSelectedItem();
      String dob=dobi.getText();
      if(flag==0)
      {
      String sql="insert into strec values('"+stnm+"','"+getbranch+"','"+sfnm+"','"+enroll+"','"+smnm+"',"+getsem+",'"+blgr+"','"+email+"','"+cat+"',"+m+",'"+add+"','"+c+"','"+s+"',"+z+",'"+gend+"','"+dob+"','"+enroll+"','"+enroll+"')";
     int i=st.executeUpdate(sql);
      st.close();
      JOptionPane.showMessageDialog(this, "New Student has been registered"); 
      sn.setText("");
      rn.setText("");
      em.setText("");
      mob.setText("");
      addrs.setText("");
      city.setText("");
      state.setSelectedIndex(0);
      fnm.setText("");
      mnm.setText("");
      dobi.setText("");
      zip.setText("");
      gender.setSelectedIndex(0);
      branc.setSelectedIndex(0);
      blg.setSelectedIndex(0);
      categ.setSelectedIndex(0);
      sem.setSelectedIndex(0);
      }
      else
      {
           // mob.setText("");
      }
       }
        catch(NumberFormatException e)
      {
          JOptionPane.showMessageDialog(this, "Fields cannot be left empty");
      }
      catch(SQLException e)
      {
        JOptionPane.showMessageDialog(this,"Enrollment no. Already exists");
      }catch(Exception e)
      {
       System.out.print(e);
      }
    }//GEN-LAST:event_submitbActionPerformed

    private void brancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brancActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brancActionPerformed

    private void brancItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brancItemStateChanged
     
    }//GEN-LAST:event_brancItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         sn.setText("");
      rn.setText("");
      em.setText("");
      mob.setText("");
      addrs.setText("");
      city.setText("");
      zip.setText("");
      okb.setVisible(true);
      updateb.setVisible(true);
      updateb1.setVisible(true);
      jButton3.setVisible(false);
      submitb.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void okbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbActionPerformed
      try
      {
          Statement st=con.createStatement();
          String in=rn.getText();
          String sql="select enroll from strec where enroll='"+in+"'";
          ResultSet rs=st.executeQuery(sql);
          if(rs.next())
          {
              rn.setEnabled(false);
              String sq="select * from strec where enroll='"+in+"'";
              ResultSet t=st.executeQuery(sq);
              if(t.next())
              {
                  categ.setSelectedItem(t.getString(9));
                  String s=t.getString(1);
                  sn.setText(s);
                  String s1=t.getString(3);
                  fnm.setText(s1);
                  String s2=t.getString(5);
                  mnm.setText(s2);
                  int s3=t.getInt(6);
                   sem.setSelectedIndex(s3-1);
                   String s4=t.getString(16);
                   dobi.setText(s4);
                   String s5=t.getString(8);
                   em.setText(s5);
                   long s6=t.getLong(10);
                   gender.setSelectedItem(t.getString(15));
                   branc.setSelectedItem(t.getString(2));
                   mob.setText(s6+"");
                   String s7=t.getString(11);
                   addrs.setText(s7);
                   String s8=t.getString(12);
                   city.setText(s8);
                   blg.setSelectedItem(t.getString(7));
                   state.setSelectedItem(t.getString(13));
                   int zi=t.getInt(14);
                   zip.setText(zi+"");
              }
          }
          else
          {
              JOptionPane.showMessageDialog(this, "Enter a valid Enrollment number"); 
              rn.setText("");
          }
      }
      catch(NumberFormatException e)
      {
          JOptionPane.showMessageDialog(this, "Fields cannot be left empty");
      }
      catch(Exception e)
      {
          System.out.println(e);
      }
       
    }//GEN-LAST:event_okbActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
       try
       {
           Statement st=con.createStatement();
           String enro=rn.getText();
           String stnm=sn.getText();
      String sfnm=fnm.getText();
      String smnm=mnm.getText();
      String blgr=(String)blg.getSelectedItem();
      String cat=(String)categ.getSelectedItem();
      //String enroll=rn.getText();
      String email=em.getText();
      long m=Long.parseLong(mob.getText());
      int z=Integer.parseInt(zip.getText());
      String add=addrs.getText();
      String c=city.getText();
      String s=(String)state.getSelectedItem();
      String getbranch=(String)branc.getSelectedItem();
      int getsem=Integer.parseInt((String)sem.getSelectedItem());
      String gend=(String)gender.getSelectedItem();
      String dob=dobi.getText();
       String sq="update strec set studentname='"+stnm+"',fname='"+sfnm+"',mname='"+smnm+"',bg='"+blgr+"',branch='"+getbranch+"',semester="+getsem+",dob='"+dob+"',email='"+email+"',category='"+cat+"',address='"+add+"',mob="+m+",city='"+c+"',state='"+s+"',zip="+z+" where enroll='"+enro+"'";    
       int i=st.executeUpdate(sq);
       JOptionPane.showMessageDialog(this, "Records Updated");
       st.close();
       okb.setVisible(false);
       updateb.setVisible(false);
       updateb1.setVisible(false);
       submitb.setVisible(true);
       jButton3.setVisible(true);
       rn.setEnabled(true);
      sn.setText("");
      rn.setText("");
      em.setText("");
      mob.setText("");
      dobi.setText("");
      addrs.setText("");
      city.setText("");
      state.setSelectedIndex(0);
      fnm.setText("");
      mnm.setText("");
      zip.setText("");
      gender.setSelectedIndex(0);
      branc.setSelectedIndex(0);
      blg.setSelectedIndex(0);
      categ.setSelectedIndex(0);
      sem.setSelectedIndex(0);
       }
       catch(Exception w)
       {
           System.out.println(w);
       }
    }//GEN-LAST:event_updatebActionPerformed

    private void mnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmActionPerformed

    private void updateb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateb1ActionPerformed
         
        try
        {
            Statement st=con.createStatement();
           String enro=rn.getText();
           String stnm=sn.getText();
           String sfnm=fnm.getText();
           String smnm=mnm.getText();
           String blgr=(String)blg.getSelectedItem();
           String cat=(String)categ.getSelectedItem();
      //String enroll=rn.getText();
           String email=em.getText();
           long m=Long.parseLong(mob.getText());
           int z=Integer.parseInt(zip.getText());
           String add=addrs.getText();
           String c=city.getText();
           String s=(String)state.getSelectedItem();
           String getbranch=(String)branc.getSelectedItem();
           int getsem=Integer.parseInt((String)sem.getSelectedItem());
           String gend=(String)gender.getSelectedItem();
           String dob=dobi.getText();
           String sq="delete from strec where enroll='"+enro+"'";    
           int i=st.executeUpdate(sq);
           JOptionPane.showMessageDialog(this, "Records have been Deleted");
           st.close();
           okb.setVisible(false);
           updateb.setVisible(false);
           updateb1.setVisible(false);
           submitb.setVisible(true);
           jButton3.setVisible(true);
           rn.setEnabled(true);
           sn.setText("");
           rn.setText("");
           em.setText("");
           mob.setText("");
           dobi.setText("");
           addrs.setText("");
           city.setText("");
           state.setSelectedIndex(0);
           fnm.setText("");
           mnm.setText("");
           zip.setText("");
           gender.setSelectedIndex(0);
           branc.setSelectedIndex(0);
           blg.setSelectedIndex(0);
           categ.setSelectedIndex(0);
           sem.setSelectedIndex(0);
            
        }catch(Exception e)
        {
         System.out.println(e);
        }
    }//GEN-LAST:event_updateb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nsr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nsr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrs;
    private javax.swing.JComboBox<String> blg;
    private javax.swing.JComboBox<String> branc;
    private javax.swing.JComboBox<String> categ;
    private javax.swing.JTextField city;
    private javax.swing.JTextField dobi;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fnm;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mnm;
    private javax.swing.JTextField mob;
    private javax.swing.JButton okb;
    private javax.swing.JTextField rn;
    private javax.swing.JComboBox<String> sem;
    private javax.swing.JTextField sn;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JButton submitb;
    private javax.swing.JButton updateb;
    private javax.swing.JButton updateb1;
    private javax.swing.JTextField us;
    private javax.swing.JTextField zip;
    // End of variables declaration//GEN-END:variables
}
